Microsoft Windows [Version 10.0.19042.928]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Brandon>call djangostack\scripts\activate

(DjangoStack) C:\Users\Brandon>cd djangostack\django\django_intro

(DjangoStack) C:\Users\Brandon\DjangoStack\Django\Django_intro>django-admin startproject books_authors

(DjangoStack) C:\Users\Brandon\DjangoStack\Django\Django_intro>cd books_authors

(DjangoStack) C:\Users\Brandon\DjangoStack\Django\Django_intro\books_authors>django-admin startapp books_shell

(DjangoStack) C:\Users\Brandon\DjangoStack\Django\Django_intro\books_authors>py manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\utils\autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\core\management\commands\runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\core\management\base.py", line 387, in check
    all_issues = self._run_checks(
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\core\management\base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\core\checks\registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\core\checks\urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\core\checks\urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\utils\functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\urls\resolvers.py", line 579, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\utils\functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\urls\resolvers.py", line 572, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1264.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Brandon\DjangoStack\Django\Django_intro\books_authors\books_authors\urls.py", line 20, in <module>
    path('', include("books_shell.url")),
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1264.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'books_shell.url'
Traceback (most recent call last):
  File "C:\Users\Brandon\DjangoStack\Django\Django_intro\books_authors\manage.py", line 21, in <module>
    main()
  File "C:\Users\Brandon\DjangoStack\Django\Django_intro\books_authors\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\core\management\base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\core\management\commands\runserver.py", line 60, in execute
    super().execute(*args, **options)
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\core\management\base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\core\management\commands\runserver.py", line 95, in handle
    self.run(**options)
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\core\management\commands\runserver.py", line 102, in run
    autoreload.run_with_reloader(self.inner_run, **options)
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\utils\autoreload.py", line 598, in run_with_reloader
    start_django(reloader, main_func, *args, **kwargs)
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\utils\autoreload.py", line 583, in start_django
    reloader.run(django_main_thread)
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\utils\autoreload.py", line 301, in run
    self.run_loop()
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\utils\autoreload.py", line 307, in run_loop
    next(ticker)
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\utils\autoreload.py", line 347, in tick
    for filepath, mtime in self.snapshot_files():
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\utils\autoreload.py", line 363, in snapshot_files
    for file in self.watched_files():
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\utils\autoreload.py", line 262, in watched_files
    yield from iter_all_python_module_files()
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\utils\autoreload.py", line 103, in iter_all_python_module_files
    return iter_modules_and_files(modules, frozenset(_error_files))
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\utils\autoreload.py", line 139, in iter_modules_and_files
    if not path.exists():
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1264.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 1407, in exists
    self.stat()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1264.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 1221, in stat
    return self._accessor.stat(self)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '<frozen importlib._bootstrap>'

(DjangoStack) C:\Users\Brandon\DjangoStack\Django\Django_intro\books_authors>py manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 17 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
April 18, 2021 - 17:01:10
Django version 2.2.4, using settings 'books_authors.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

(DjangoStack) C:\Users\Brandon\DjangoStack\Django\Django_intro\books_authors>py manage.py makemigrations
Traceback (most recent call last):
  File "C:\Users\Brandon\DjangoStack\Django\Django_intro\books_authors\manage.py", line 21, in <module>
    main()
  File "C:\Users\Brandon\DjangoStack\Django\Django_intro\books_authors\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    django.setup()
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\apps\config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1264.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Brandon\DjangoStack\Django\Django_intro\books_authors\books_shell\models.py", line 4, in <module>
    class Book(models.Model):
  File "C:\Users\Brandon\DjangoStack\Django\Django_intro\books_authors\books_shell\models.py", line 5, in Book
    title =model.CharField(max_length=200)
NameError: name 'model' is not defined

(DjangoStack) C:\Users\Brandon\DjangoStack\Django\Django_intro\books_authors>py manage.py makemigrations
Traceback (most recent call last):
  File "C:\Users\Brandon\DjangoStack\Django\Django_intro\books_authors\manage.py", line 21, in <module>
    main()
  File "C:\Users\Brandon\DjangoStack\Django\Django_intro\books_authors\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    django.setup()
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "C:\Users\Brandon\DjangoStack\lib\site-packages\django\apps\config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1264.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Brandon\DjangoStack\Django\Django_intro\books_authors\books_shell\models.py", line 4, in <module>
    class Book(models.Model):
  File "C:\Users\Brandon\DjangoStack\Django\Django_intro\books_authors\books_shell\models.py", line 6, in Book
    desc = models.Textfield(max_length=200,default='Good Book')
AttributeError: module 'django.db.models' has no attribute 'Textfield'

(DjangoStack) C:\Users\Brandon\DjangoStack\Django\Django_intro\books_authors>py manage.py makemigrations
Migrations for 'books_shell':
  books_shell\migrations\0001_initial.py
    - Create model Book
    - Create model Author

(DjangoStack) C:\Users\Brandon\DjangoStack\Django\Django_intro\books_authors>py manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, books_shell, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying books_shell.0001_initial... OK
  Applying sessions.0001_initial... OK

(DjangoStack) C:\Users\Brandon\DjangoStack\Django\Django_intro\books_authors>py manage.py shell
Python 3.9.4 (tags/v3.9.4:1f2e308, Apr  4 2021, 13:27:16) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from books_shell import *
>>> csharp = Book.objects.create(title = "C Sharp")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'Book' is not defined
>>> from books_shell import *
>>> from books_shell.models import *
>>> csharp = Book.objects.create(title = "C Sharp")
>>> java = Book.objects.create(title = "Java")
>>> python = Book.objects.create(title = "Python")
>>> php = Book.objects.create(title = "PHP")
>>> ruby = Book.objects.create(title = "Ruby")
>>> jane = Author.objects.create(first_name = "Jane",last_name = "Austen")
>>> emily = Author.objects.create(first_name = "Emily",last_name = "Dickinson")
>>> fyodor = Author.objects.create(first_name = "Fyodor",last_name = "Dostoevsky")
>>> william = Author.objects.create(first_name = "William",last_name = "Shakespeare")
>>> lau = Author.objects.create(first_name = "Lau",last_name = "Tzu")
>>> exit()

(DjangoStack) C:\Users\Brandon\DjangoStack\Django\Django_intro\books_authors>py manage.py makemigrations
Migrations for 'books_shell':
  books_shell\migrations\0002_author_notes.py
    - Add field notes to author

(DjangoStack) C:\Users\Brandon\DjangoStack\Django\Django_intro\books_authors>py manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, books_shell, contenttypes, sessions
Running migrations:
  Applying books_shell.0002_author_notes... OK

(DjangoStack) C:\Users\Brandon\DjangoStack\Django\Django_intro\books_authors>py manage.py shell
Python 3.9.4 (tags/v3.9.4:1f2e308, Apr  4 2021, 13:27:16) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from book_shell.models import *
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ModuleNotFoundError: No module named 'book_shell'
>>> from books_shell.models import *
>>> books_to_update = Book.objects.get(csharp)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'csharp' is not defined
>>> books_to_update = Book.objects.get(id=1)
>>> books_to_update.title = C#
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'C' is not defined
>>> books_to_update.title = "C#"
>>> books_to_update.save()
>>> authors_to_update = Author.objects.get(id=4)
>>> authors_to_update.first_name = "Bill"
>>> this_book1 = Book.objects.get(id=1)
>>> this_book2 = Book.objects.get(id=2)
>>> this_author1 = Author.objects.get(id=1)
>>> this_author.books.add(this_book1,this_book2)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'this_author' is not defined
>>> this_author1.books.add(this_book1,this_book2)
>>> this_book3 = Book.objects.get(id=3)
>>> this_book4 = Book.objects.get(id=4)
>>> this_book5 = Book.objects.get(id=5)
>>> this_author2 = Author.objects.get(id=2)
>>> this_author3 = Author.objects.get(id=3)
>>> this_author4 = Author.objects.get(id=4)
>>> this_author5 = Author.objects.get(id=5)
>>> this_author2.books.add(this_book1,this_book2,this_book3)
>>> this_author3.books.add(this_book1,this_book2,this_book3,this_book4)
>>> this_author4.books.add(this_book1,this_book2,this_book3,this_book3,this_book4,this_book5)
>>> this_author5.books.add(this_book2)
>>> Books.objects.get(id=3)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'Books' is not defined
>>> Book.objects.get(id=3)
<Book: Book object (3)>
>>> this.book3.authors.all()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'this' is not defined
>>> this_book3.author.all()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'Book' object has no attribute 'author'
>>> this_book3.authors.all()
<QuerySet [<Author: Author object (2)>, <Author: Author object (3)>, <Author: Author object (4)>]>
>>> this_author2.books.remove(this_book3)
>>> this_book3.authors.all()
<QuerySet [<Author: Author object (3)>, <Author: Author object (4)>]>
>>> this_author3.books.all()
<QuerySet [<Book: Book object (1)>, <Book: Book object (2)>, <Book: Book object (3)>, <Book: Book object (4)>]>
>>> this_book5.authors.all()
<QuerySet [<Author: Author object (4)>]>
>>>